debian/control
lxpanel-plugin/Makefile
lxpanel-plugin/kano_updater.c

Related to: https://github.com/KanoComputing/peldins/issues/1540
cc @alex5imon

lxpanel-widget: Porting to lxpanel > 0.7

---

python_modules

Related to https://github.com/KanoComputing/kano-settings/pull/186

Adds docopt to the installed python modules

---

debian/changelog
kano_updater/utils.py

Include iU

---

kano_updater/stages.py
kano_updater_gui/media/css/updater.css
kano_updater_gui/text.py

KanoComputing/peldins#1582
To provide a more responsive feel, split the package installation stage
between downloading and installing the packages.
@pazdera @skarbat Does this look like it might break anything?

Squeeze in a 4th stage - Optimising your Kano

---

kano_updater_gui/media/css/updater.css

fix colours for public service announcement next to (!) bang.png

---

bin/kano-updater
kano_updater/ui/main.py

To allow checking for updates only if a certain minimum period has
expired, add a parameter to the command line options.
cc @pazdera

Add updater check interval command

---

bin/kano-updater
kano_updater/utils.py

Use a PID file to prevent multiple instances.
cc @pazdera

Ensure that the updater isn't already running

---

bin/kano-updater
kano_updater/progress.py
kano_updater/ui/main.py

So it pops up to cover the window before we exit from the Gtk main loop.
@tombettany Please review.

Relaunching the updater sooner

---

kano_updater/ui/install_window.py

If the install thread should die unexpectedly then the UI will just
hang. Prevent this behaviour by polling to see if the install thread is
still alive.
cc @pazdera

UI: Periodically check that install is running

---

kano_updater/ui/progress.py

For now just have the abort progress event just do the same as an error.

Implement the abort alert

---

bin/kano-updater

cc @tombettany We need to merge this before releasing today.

Setting log level back to info before the release

---

bin/kano-updater

I think this fixes the extra popups.

Don't remove the pidfile in early exit case

---

kano_updater/ui/available_window.py

To avoid interference with minecraft.
Related to: https://github.com/KanoComputing/peldins/issues/1757
cc @Ealdwulf @alex5imon

check-gui: Raise instead of keeping above

---

python_modules

Not entirely sure but this could potentially fix the json problem encountered, Radek? @pazdera

Freezing the installation of python requests library version

---

kano_updater/ui/media/css/updater.css

Increasing the font size of the info text shown during installation

---

kano_updater/scenarios.py

Generate an initial character for users that update

Create a random character on update to 2.0

---

python_modules

Related to: https://github.com/KanoComputing/peldins/issues/1794
cc @alex5imon

Freeze the version of youtube-dl

---

lxpanel-plugin/kano_updater.c

The update check was set to an incorrect interval.
@alex5imon It's a small change but we don't have to merge it if you don't want to.

Increase the check interval to 7 days

---

debian/control
kano_updater/commands/install.py
kano_updater/progress.py
kano_updater/ui/install_window.py
kano_updater/ui/progress.py

This commit makes the install command check for free space before
anything happens. If there's less than 1GB left, it won't proceed
with the install and optionally tries to expand the card.
Related to: https://github.com/KanoComputing/peldins/issues/1798
cc @alex5imon  @tombettany

install: Make sure there's enough free space available

---

po/PYPOTFILES

Updated list of Python modules using i18n literals

---

kano_updater/auxiliary_tasks.py

This should fix it
cc @tombettany @skarbat

Using _ for an unused variable conflicts with gettext

---

debian/control

This should fix the updater fail with lxpanel.

Adding a runtime dependency on lxpanel

---

kano_updater/commands/install.py
kano_updater/ui/main.py

boot: Relaunch the updater when it's interrupted

---

bin/kano-updater
lxpanel-plugin/kano_updater.c

https://github.com/KanoComputing/peldins/issues/1885

Added dialog if no updates available

---

kano_updater/scenarios.py

The name of the character has been changed

Update 134 to 200 post update scenario

---

bin/kano-updater
debian/control
kano_updater/utils.py

Make sure the updater doesn't freeze without having to depend on kano-widgets

Notifications failsafe

---

kano_updater/scenarios.py

https://github.com/KanoComputing/peldins/issues/1943

Added telnet, required by use-the-force script

---

kano_updater/commands/download.py

update updater copy

---

kano_updater/ui/media/flappy-judoka/src/graphics/display.py
kano_updater/ui/views/install.py

Addresses https://github.com/KanoComputing/peldins/issues/2011 and https://github.com/KanoComputing/peldins/issues/2010
@alex5imon Could you please review this?

Invisible cursor and updater label hiding

---

bin/expand-rootfs

These changes should be compatible with wheezy (no systemd specific constructs used). Therefore I'm proposing this as a change to master, and we can rebase/cherry-pick it on jessie as well.
@pazdera @radujipa 
For https://github.com/KanoComputing/peldins/issues/1992

Fix expand-rootfs for jessie

---

lxpanel-plugin/kano_updater.c

@alex5imon could you please review this?

Downloads Completed notification copy change

---

kano_updater/auxiliary_tasks.py

Adding a new aux task.
cc @radujipa @tombettany @alex5imon

Upload tracking data on update

---

kano_updater/commands/install.py
kano_updater/ui/views/finish.py
kano_updater/utils.py

related to https://github.com/KanoComputing/peldins/issues/2122

Replaced shutdown/reboot with systemctl

---

kano_updater/scenarios.py
kano_updater/utils.py

Related to: https://github.com/KanoComputing/peldins/issues/2216
cc @skarbat @alex5imon

220->230: Install rsync during update

---

debian/changelog
kano_updater/scenarios.py
kano_updater/utils.py

towards https://github.com/KanoComputing/peldins/issues/2162

Install Make Light on 2.3.0

---

kano_updater/scenarios.py

This PR adds spi and gpio groups, and adds the users to them, to allow access to the gpio and spi ports without sudo. For https://github.com/KanoComputing/peldins/issues/2209
@pazdera @skarbat @alex5imon

Add gpio and spi groups, and add all users to them.

---

kano_updater/auxiliary_tasks.py
kano_updater/utils.py

Also run sync for all installed users on the kit
This PR is useful for https://github.com/KanoComputing/peldins/issues/2179

Prune kano-content during the aux tasks

---

kano_updater/version.py

cc @alex5imon @convolu @tombettany @pazdera @Ealdwulf @skarbat

Changed the Kanux Version to 2.3.0

---

kano_updater/ui/main.py

Related to: https://github.com/KanoComputing/peldins/issues/2257
cc @radujipa @convolu @tombettany

Set a different state on reboot

---

kano_updater/auxiliary_tasks.py

This will check whether we updated any of the app icons and allow users to redownload them.
cc @tombettany @alex5imon @convolu

check-for-app-updates: New aux task

---

debian/control
kano_updater/ui/views/install.py

Related to https://github.com/KanoComputing/Kerberos/issues/4

Moved from hardware dependent feature to performance dependent

---

kano_updater/ui/main.py

Related to https://github.com/KanoComputing/peldins/issues/2067, but this one is optional.

Removed dialog asking to continue update after reboot

---

kano_updater/scenarios.py

Add pre and post update scenarios for 2.4.0.
cc @radujipa @Ealdwulf @alex5imon

OS v2.4.0: Add update scenarios

---

debian/changelog
kano_updater/scenarios.py
kano_updater/version.py

@skarbat @alex5imon @tombettany

Bump version number for 3.0.1

---

kano_updater/commands/install.py

Should have been all updated after a full update.

Clean list of updatable independent packages

---

debian/changelog
kano_updater/scenarios.py
kano_updater/version.py

Add changes for next OS version.

---

kano_updater/scenarios.py

This PR adds post-update scenario to add 'enable_uart=1' to config.txt. Some complication is required to be compatible with older versions of kano_settings. I have tested both (by deliberatily breaking kano-settings so the exception case happens).
For https://github.com/KanoComputing/peldins/issues/2369
@tombettany @alex5imon

Add uart config for make-light

---

kano_updater/scenarios.py

Adding termination of config @tombettany

Terminate pi3-specific config.

---

kano_updater/scenarios.py

Related to https://github.com/KanoComputing/kano-overworld/issues/504
cc @Ealdwulf @tombettany

Skipping Overworld onboarding and creating flag for Dashboard

---

debian/changelog
kano_updater/scenarios.py
kano_updater/version.py

@tombettany @radujipa 
For https://github.com/KanoComputing/peldins/issues/2397

Bump version to 3.3.0

---

kano_updater/scenarios.py

For https://github.com/KanoComputing/peldins/issues/2384,
if we decide we like the audio dither, we can push it to updating users too.
@tombettany @alex5imon

Push audio dither setting to updating users.

---

kano_updater/scenarios.py

This PR adds an update scenario to restore scratch projects which were saved to the wrong place.
@tombettany @radujipa 
It's based off the dither one, if we don't push that I'll rebase it.

Restore scratch files.

---

debian/changelog
kano_updater/scenarios.py
kano_updater/version.py

Related to https://github.com/KanoComputing/peldins/issues/2423

Version bump for Kano OS 3.4.0

---

debian/changelog
kano_updater/scenarios.py
kano_updater/version.py

Related to https://github.com/KanoComputing/peldins/issues/2545

Version bump for Kano OS v3.5.0

---

debian/changelog
kano_updater/scenarios.py
kano_updater/version.py

Related to https://github.com/KanoComputing/peldins/issues/2631

Version bump for Kano OS v3.6.0

---

debian/changelog
kano_updater/scenarios.py
kano_updater/version.py

Bump version for next release.
@skarbat @tombettany

Version: Bump to 3.8.0

---

bin/kano-updater

Reopening https://github.com/KanoComputing/kano-updater/pull/202

Freeing PID file should be the last operation executed

---

kano_updater/scenarios.py

Change GPU_mem to 256 for 3.8.0

---

bin/expand-rootfs

Not for merging yet, just putting this here before I lose it.

Live expand

---

debian/changelog
kano_updater/scenarios.py

Please ignore this, git is going crazy.

Report UI progress in PostUpdate scenario when installing 3rd party apps
