KanoComputing/kano-updater

bin/kano-updater
Migrated to the new tracker and added some new tracking points. Neil should now be able to tell when people update, from which version and whether the update finished properly.
A few formatting changes on the way.
Related to:
https://github.com/KanoComputing/peldins/issues/1358
https://github.com/KanoComputing/kano-profile/pull/201
cc @alex5imon @skarbat
=> Migrating to the new tracker

bin/check-for-updates
The image used for the check for updates screen was moved but the path
wasn't updated, so update it.
=> Fix image in the check for updates window

kano_updater_gui/header.py, kano_updater_gui/stage.py
makes it easier to change height/width of the main layout elements and computes PROGRESS_HEIGHT from the height values it depends on (instead of using a fixed value).
=> move fixed layout width/height values into constants

.gitignore, TRANSLATION.md, bin/check-for-updates, bin/kano-updater, bin/kano-updater-gui, debian/changelog, debian/control, debian/install, debian/rules, kano_updater/utils.py, kano_updater_gui/header.py, kano_updater_gui/text.py, lxpanel-plugin/kano_updater.c, po/CPOTFILES, po/Makefile, po/PYPOTFILES, po/de.po
Essentially the same as https://github.com/KanoComputing/kano-updater/pull/63.
The differences being:
- Rebased on the `master`'s `HEAD` to resolve conflict
- Removed commit https://github.com/hzulla/kano-updater/commit/8d9ceab3ef4e0a94f00a5755c2eb9e7ba9843688 because this functionality has been moved into `kano-toolset` and thus there is now a dependency on `v1.3-10` (and https://github.com/hzulla/kano-updater/commit/43d492728fde4888e59e1a8fb301bdc03f2b8ef2 which removes something in the aforementioned commit)
- Bumped the version to allow translation functionality dependent dependencies :-P
- Added copyright information to the German translation and to the `Makefile` to auto-generate this information
@hzulla Any objections?
@Ealdwulf @skarbat @carolineclark @pazdera @convolu @alex5imon …
=> I18n gettext hooks for kano-updater-gui, kano-updater and check-for-updates (3rd try)

kano_updater/ui/install_window.py, kano_updater/ui/main.py
Missed some things with https://github.com/KanoComputing/kano-updater/pull/75
Other half of c00736b3a9b0ee0e14deadef50ba6d0eb902613e
Move common functionality of the update available and update downloaded
dialogs into a base class. Implement the update downloaded window. Fix
rebooting image to stop after one loop and actually reboot when it
happens. Fix the install screen not progressing when the download is
complete.
=> Update downloaded GUI: Add update downloaded GUI

kano_updater/ui/install_window.py
KanoComputing/peldins#1617
Utilise the killall functionality through kano-launcher.
cc @pazdera @Ealdwulf
=> Kill other applications when installing

debian/postinst
check-for-updates no longer exists so it is unnecessary to keep the
entry in the sudoers file.
=> Remove check-for-updates entry in the sudoers file

kano_updater/ui/available_window.py
The download button on the GUI was using its own system for making
itself low priority - use the util function instead.
=> Launch download from GUI with low priority

bin/kano-updater, kano_updater/commands/clean.py, kano_updater/ui/main.py, kano_updater/utils.py
Split the `boot-check` command into a new clean command which corrects
the state of the status file if it is left unclean and move the
boot check window (along with the splash relaunch) into a `ui`
subcommand.
@pazdera I'm sure that I've missed something but this is a start
=> Update the CLI interface

python_modules
* This installation should remove further complains from pip:
"InsecurePlatformWarning: A true SSLContext object is not available"
=> Installing requests security module, to remove further warnings

python_modules
* Square brackets name a dependency package,
so removing the additional line to install "requests",
because pip complains with an error, saying it is covered
by the previous line.
cc @Ealdwulf
=> Fixing pip requests installation

bin/kano-updater, kano_updater/commands/check.py, kano_updater/ui/main.py
So the updater doesn't show the dialog when there is an update from
a previous check, but it wasn't supposed to check in the first place
due to the interval guards being set.
=> Moving the interval guards outside of the check_for_updates function

bin/kano-updater, debian/changelog
This should be used from kano-uixinit at the end of the init flow to
make sure the user isn't prompted for update during the first 24 hours
from creating his account.
Needs a change in kano-uixinit which will be ready shortly.
=> bin: Adding the first-boot subcommand

kano_updater/commands/download.py, kano_updater/commands/install.py
These can arise from special characters such as (>, < and others).
cc @Ealdwulf @alex5imon 
Related to: https://github.com/KanoComputing/peldins/issues/1803
=> pip: Quoting package names to avoid shell errors

bin/repair-homedir-permissions, kano_updater/scenarios.py
* A process will go through all home directories
and apply KanoOS 2.0 permissions on sensitive files & dirs (tracker, logs)
=> Adding a new step in the upgrade stage to fix homedire permissions

bin/kano-updater, lxpanel-plugin/kano_updater.c
The updater notifications will now use the new OS X style notification
buttons. This commit also adds a new notifications to indicate the
download started.
Related to: https://github.com/KanoComputing/peldins/issues/1841 https://github.com/KanoComputing/kano-widgets/pull/17
=> updater-notifications: New notifications style

kano_updater/auxiliary_tasks.py
This will stop the updater from freezing and log the traceback, should there be a problem in the home directory.
Related to: https://github.com/KanoComputing/peldins/issues/1820
cc @alex5imon @tombettany @skarbat @Ealdwulf
=> update_home_folders_from_skel: Run in a try

lxpanel-plugin/kano_updater.c
@mkeegan found a few bugs in the notifications flow. This should fix them.
The problems:
* Downloading notification not being displayed (syntax error in a json)
* The confirmation dialog being displayed when clicking the widget manually (added noconfirm).
* The updates-downloaded notification not displayed on reboot.
=> Pre update flow fixes

kano_updater/ui/main.py
The new boot window changelog is a Gtk2 window but the rest of the
application uses Gtk3. If one is loaded then the other will fail so
migrate the loading of the libraries into the scope of the functions
that require them.
cc @pazdera
=> Fix the new boot window not appearing

python_modules
The Sentry module seems to be the only package that needs the futures module, so we're freezing the version.  Later versions of the futures modules seem to break the sentry module, which breaks the Ultimate Parental Control.
=> Froze futures module version

bin/kano-updater, kano_updater/commands/clean.py, kano_updater/status.py, lxpanel-plugin/kano_updater.c
KanoComputing/peldins#1902
When the updater is in full-screen install mode, it will change its
status file to account for the progress made in the install. This,
however, generates notifications about the status of the process which
are visible above the GUI itself. Prevent this by providing a flag in
the status file which can disable these messages.
Integrate this flag to suppress messages when installing in full-screen
mode and reset it when a `clean` is called.
KanoComputing/peldins#1791
Also pauses all notifications until the updater has run its course so that
they are not lost but not shown during this time.
cc @pazdera
=> Notifications: Suppress messages when the GUI is running

bin/kano-updater, kano_updater/commands/clean.py, kano_updater/status.py, lxpanel-plugin/kano_updater.c
The original flag was called `is_gui_running` but this can be confusing
and suppressing the notifications may be desired in situations other
than when the GUI is running so rename it to a more sensible name
(`notifications_muted`).
cc @pazdera
=> Notifications: Rename flag for muting notifications

bin/kano-updater, debian/control
Instead of each package handling i18n initialisation independently, use
the `kano-i18n` library.
cc @pazdera
=> i18n: Use the kano-i18n library for i18n init

bin/kano-updater
If the logs are flushed before the end, some of the logs won't be saved
during the update process so move them to the last of the tasks.
cc @pazdera
=> Flush the logs as the last step when closing

kano_updater/commands/clean.py, kano_updater/ui/main.py
KanoComputing/peldins#1915
When booting, if the updater had to reboot to be able to continue, a
message is shown to prompt the user to carry on with the update. This
accompanies a status change which triggers a notification. If this is
the case, disable the notification so that two calls to action aren't
present.
cc @pazdera
=> Notifications: Don't show on boot if a dialog appears

lxpanel-plugin/kano_updater.c
KanoComputing/peldins#1923
When the notification widget is initialised, the status file is checked
and, if appropriate, a notification may be triggered. This causes
unknown lock-ups when a user attempts to click the buttons on the
notification.
Instead, remove this call in the constructor and rely on the status file
monitor to trigger the notifications. The Updater boot check modifies
the file anyway so the notification is triggered but without the
lock-up.
cc @pazdera @Ealdwulf @skarbat @convolu
=> Notification: Remove status file check on init

kano_updater/commands/download.py, kano_updater/commands/install.py, kano_updater/paths.py
With these changes we replace the use of the deprecated `--no-install` while downloading
the packages.
As the pip documentation now suggests we should create and maintain our own cache.
This also changes the way we install packages as we need to look in the newly created cache.
A failsafe method has been added that ensures that the packages are installed even if they are
not present in the cache
=> Fix no-install

kano_updater/utils.py
This is no longer used in the updater and should be removed.
I moved the function into kano_apps where it's still used.
We should remove it in the next release (I don't want to risk removing it today).
cc @alex5imon @tombettany @skarbat
=> Deprecating get_dpkg_dict

bin/expand-rootfs, bin/kano-empty-trash, kano_updater/commands/install.py
This PR adds a command kano-empty-trash to empty the trash.
For https://github.com/KanoComputing/peldins/issues/1917
It is called in the updater and in expand-rootfs.
=> Add way to empty the trash.

debian/changelog
The X.Y format of the version may cause issues and goes against the assumptions about urgent updates. This rectifies this
=> Use the format X.Y.Z-B for the package version no

kano_updater/scenarios.py
This fixes broken updates currently in production to Kano OS 2.2.0 in the scenarios.
@tombettany @pazdera @convolu Could you please review this?
=> Fixes updates to latest Kano OS 2.2.0

bin/kano-updater, kano_updater/commands/check.py, kano_updater/status.py
Added the capability of setting a time slot after the first ever boot in which update
notifications are supressed. The time slot is currently three days.
WARNING: This is still susceptible to date/time changes after the first boot!
@alex5imon @tombettany @pazdera could you please review this?
=> First boot countdown

kano_updater/ui/media/flappy-judoka/bin/flappy-judoka, kano_updater/ui/media/flappy-judoka/src/core/gamestate.py
Tracking events added:
- session length: how long the game is being run for
- action: when the game is being launched
- data: player score when flappy dies
@alex5imon @pazdera could you please review this?
=> Added tracking to Flappy Judoka

kano_updater/ui/main.py
When relaunching the updater, a relaunch splash screen is created to
mask the underlying updater restart. This relies on passing the splash
screen PID between updater instances so that the latter version can kill
the splash screen.
The handling of both passing the PID of the splash screen to the
`exec()` call for relaunch and killing the splash screen after relaunch
were within the same function so some variables were used twice (to mean
both the PID of the launched splash and the currently running splash
PID) which lead to undetermined behaviour. Fix this by separating the
two uses.
@pazdera @radujipa could you review?
=> Relaunch: Fix passing splash PID between instances

kano_updater/ui/views/install.py
Killing the daemon needs to happen when we are sure a reboot is going to happen.
- added the `pkill` at the same time as enabling `flappy-judoka`
@alex5imon @tombettany could you please review this?
related to https://github.com/KanoComputing/peldins/issues/2119
=> Killing the notifications-daemon to eliminate frozen notifications

kano_updater/scenarios.py
This PR removes the `modemmanager` package during the preupdate scenario to OS version 2.3.0.
As there is a minor chance that a user manually installed the package, we first check that is was installed automatically (which btw would also be the case if the user needs it from a different package that he has installed)
=> Remove modemmanager package on 2.3.0

kano_updater/commands/install.py
We removed the brain reference from the kano-apps dialog. Removing it from here as well.
What do you guys think? @neue @radujipa @alex5imon
=> Removing the brain reference from the updater

debian/control
The PostUpdate scenarios require the use of `open_locked`'s `timeout`
parameter but if `kano-toolset` hasn't been updated to include this
feature before the Updater runs the cached version of the `kano.utils`
module is used and hence fails. Resolve this by bumping the dependency
requirement.
@Ealdwulf @pazdera @convolu do you think that this will fix the caching issue?
=> Deps: Bump kano-toolset dependency

bin/kano-updater, kano_updater/commands/download.py, kano_updater/status.py
During the relaunch of the updater, somehow the state gets reset to
`NO_UPDATES` which causes the relaunch to exit prematurely. Prevent this
from happening by forcing the state to be the value that it should be
after a relaunch.
@pazdera @convolu @radujipa to review
=> Relaunch: Ensure that update proceeds after relaunch

bin/kano-updater, debian/changelog, kano_updater/ui/install_window.py, kano_updater/ui/media/flappy-judoka/src/graphics/display.py, kano_updater/ui/media/flappy-judoka/src/utils.py, kano_updater/ui/progress.py, kano_updater/ui/relaunch_window.py, kano_updater/ui/views/install.py, kano_updater/utils.py
This is supposed to act as a safe guard when the Updater fails for whatever reason and FlappyJudoka was launched. Previously, several processes were killed in order to keep the game on top of the window. This is no longer needed and if the updater crashes, the OS will not be in an 'unstable' state anymore.
@tombettany @pazdera @convolu
=> Relaunching Lxpanel in the cleanup if FlappyJudoka was launched

kano_updater/scenarios.py
When installing Bluez as a dependency of `kano-settings`, the
configuration can fail resulting in a broken update. Attempt to fix by
installing Bluez before anything else.
=> OS v2.4.0: Add fix for Bluez dependency issues

bin/kano-updater, kano_updater/apt_wrapper.py, kano_updater/commands/check.py, kano_updater/commands/clean.py, kano_updater/commands/install.py, kano_updater/special_packages.py, kano_updater/status.py
NB this isn't ready to merge, but I'd like people's opinion on whether this is the right approach to installing the package @tombettany @alex5imon @skarbat @radujipa 
This PR:
* Adds a list of packages in 'special_packages.py' which don't trigger an OS update.
*  Introduces a new updater command 'kano-updater update_ind_pkg <pkg>'. This enters a new state  'INSTALLING_INDEPENDENT'  and installs the package, then transitions to UPDATES_INSTALLED. The updater is prevented from going into install mode when an independent package is being installed and vice versa.
* Adds a new command 'avail_ind_pkgs' which lists the spcial packages which are available to be updated. This may be removed if we decide on a different way of communicating with kano-dashboard.
Questions:
* is UPDATES_INSTALLED the …
=> Separate update

kano_updater/apt_wrapper.py, kano_updater/commands/check.py, kano_updater/commands/clean.py, kano_updater/commands/install.py
This PR fixes a problem noticed by @tombettany in that the status file wasn't being updated after installing an independent package, thus causing the gui to think it could still be installed.
While looking at this I noticed that because the list of updatable independent packages is made using whatever priority level the check command is called  with, that field in the status file coudl flip flop between having and not having the package.  Therefore I have looked through the use of priority and made a couple of changes:
Generally, only deal with independent packages *independently* at ordinary priority . At URGENT priority,  treat them the same as other packages (IE< if an urgent update is pushed to an 'idependent' package, this is installed using the urgent update facility).
Detail:
* …
=> Update status.updatable_independent_packages after installing an update

debian/changelog, debian/postinst
* On Jessie, the APT url was not being updated, so no urgent updates were possible.
* Wheezy users should also get the urgent updates (not strictly necessary though, I think).
@Ealdwulf
=> Fixed Jessie urgent updates into APT during an update

bin/kano-updater, bin/kano-updater-quickcheck, debian/changelog, debian/control, debian/postinst
This PR adds fast script for querying updater status file and running kano-updater if necessary.
A dependency on jq (json query) is introduced.
@tombettany @skarbat @alex5imon  
Note that there is some maintenance cost to this as extra triggers must be added in both places.
For https://github.com/KanoComputing/peldins/issues/2327
=> Speed up kano-updater ui boot-window

kano_updater/scenarios.py
This should add the setting from https://github.com/KanoComputing/kano-settings/pull/369 for users who update.
Function copied from spi modification in 2.3.0 scenario.
@alex5imon @skarbat
=> Add fix to set `dtparam=audio=on` in /boot/config.txt

kano_updater/scenarios.py, kano_updater/version.py
This changes the new vrsion to 3.1.0 as 3.0.1 would trigger an urgent update.
@convolu @tombettany @radujipa
=> Bump to 3.1.0 to avoid triggering an urgent update.

lxpanel-plugin/kano_updater.c
KanoComputing/os-dashboard#141
The dashboard handles downloading the updates in the background
ungracefully so to combat this don't show the notifications which permit
this action.
cc @Ealdwulf @alex5imon
=> Notifications: Disable available and downloaded notifications

kano_updater/commands/install.py, kano_updater/progress.py
KanoComputing/peldins#2375
When installing the independent updates, it is possible for the source
repositories to have changed in the time between the package being
identified as having updates available and the user actually choosing to
update it. Resolve this problem by updating the APT sources immediately
before attempting to update the package.
cc @Ealdwulf @pazdera
=> Independent Pkgs: Update the sources before installing

kano_updater/commands/download.py
KanoComputing/peldins#2380
The pip download was using the `pip install --download` command during
the download phase. This has been deprecated and will be removed in pip
10 so switch to use its replacement: `pip download`.
cc @Ealdwulf @pazdera
=> Pip Download: Switch to modern "download" command

kano_updater/scenarios.py
https://trello.com/c/1QrdXt2l/92-updater-pi2-update-from-2-4-0-to-3-4-0-failed
The update of `bluez` will often fail due to its postinstall
configuration script exiting with error status when the user does not
have a bluetooth capable device present. A work-around to this was
utilised for the update from v2.3.0 - v2.4.0 via a preupdate scenario
which installed the package manually. Unfortunately, this same problem
affects users updating from v2.4.0 to later versions so make the
solution more broad to do the install independently for every update.
This has a side-effect of adding a function where pre- and post-update
scripts which should run on every update can be located.
cc @Ealdwulf @radujipa @skarbat
=> Bluez: Move bluez preinstall to happen with every update

kano_updater/utils.py
Change is_running to avoid race between readying the pid file, checking its existence, and writing to it.
@tombettany @radujipa
=> Avoid pidfile race

debian/control, kano_updater/scenarios.py
This change should fix the automatic tty login being lost, after upgrading from several older OS versions.
@tombettany @Ealdwulf
=> Fixes for lost automatic login after upgrade

kano_updater/scenarios.py
This change applies the new systemd style in kano-init during an upgrade.
The side effect was that Overture was being launched on top of Dashboard.
Sorry, it will probably clash with: https://github.com/KanoComputing/kano-updater/pull/226
@radujipa @tombettany
=> Correctly enable Overture during an upgrade

bin/kano-updater
This changeset fixes the issue where the home button is visible on the Dashboard on bootup.
@radujipa
=> Fix for updater to show the home button on exit

kano_updater/scenarios.py
After an upgrade from 2.4.0, kano-init drags the overture app package,
which starts in multi-user mode. This mistakenly goes through the onboarding on reboot.
We did not care too much about this systemd mode previously.
Fixed by forcing kano-init to prepare the system for a regular graphics mode Dashboard bootup.
@tombettany @radujipa
=> Fix overture kicking in after an upgrade

bin/kano-updater-quickcheck, debian/changelog
Complements this PR: https://github.com/KanoComputing/os-dashboard/pull/329
=> Provide a --dry-run option to query udpates availability

debian/changelog, kano_updater/scenarios.py, kano_updater/version.py
Bump version for next release.
Needed in `master` regardless of the image generation approach.
=> Version: Bump to 3.9.1-Lovelace

debian/changelog, kano_updater/scenarios.py
This change in a post-update from 3.11.0 to 3.12.0 is to ensure
that the local ALSA config files are removed such that only the
system ones are kept (see kano-settings, kano-desktop).
=> Removed local ALSA config files from all users

kano_updater/scenarios.py
During the post-update scenarios the parental setting is set to be COPPA
compliant. When we do this, the `kano-settings-cli` command it used but
this blocks while the sentry proxy server is restarted and then owns the
server itself and thus never returns, causing a hang. To resolve this,
trigger the parental setting configuration in the background and wait
for the process to establish itself.
=> COPPA: Set the parental setting in the background

kano_updater/scenarios.py
During the update we were setting the parental restriction in order to
comply with COPPA. This was causing problems with process ownership and
the updater hanging so remove it for this update and resolve the issue
for COPPA go-live date.
=> COPPA: Remove parental setting on update
